# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bradley J Kavanagh
email: bradkav@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal physics website, covering Dark Matter, Particle Physics,
  Statistics and Open Science. The site includes my publication list, CV, 
  research interests and current projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bradkav.net" # the base hostname & protocol for your site
twitter_username: bradleykavanagh
github_username:  bradkav


author: Bradley J Kavanagh
twitter:
  username: bradleykavanagh

# Build settings
#markdown: kramdown
#markdown: CommonMarkGhPages

markdown: kramdown
kramdown:
  parse_block_html: true

theme: minima

#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]

gems:
  - jekyll-seo-tag

# Google services
google_analytics: UA-88094985-1

#kramdown:
  # use Github Flavored Markdown
#  input: GFM
  # do not replace newlines by <br>s
#  hard_wrap: false
  # parse markdown inside block-level HTML tag
#kramdown: 
#  parse_block_html: true